language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3

dist: trusty
sudo: false

before_script:
- composer self-update
- composer global require fxp/composer-asset-plugin
- composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --verbose
